...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
...................................
----------------------------------------------------------------------
Ran 35 tests in 0.010s

OK
..FFFF.F..
======================================================================
FAIL: test_invalidarg (tests.test_3c3d.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/escnfs/home/mtcherny/repos/student-cse20289-fa24-mtcherny/hw/hw06/tests/test_3c3d.py", line 57, in test_invalidarg
    self.assertFalse("ambiguous option" in result)
AssertionError: True is not false

======================================================================
FAIL: test_isadir (tests.test_3c3d.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/escnfs/home/mtcherny/repos/student-cse20289-fa24-mtcherny/hw/hw06/tests/test_3c3d.py", line 53, in test_isadir
    self.assertFalse("IsADirectoryError" in result)
AssertionError: True is not false

======================================================================
FAIL: test_noexistfile (tests.test_3c3d.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/escnfs/home/mtcherny/repos/student-cse20289-fa24-mtcherny/hw/hw06/tests/test_3c3d.py", line 45, in test_noexistfile
    self.assertFalse("FileNotFoundError" in result)
AssertionError: True is not false

======================================================================
FAIL: test_nofile (tests.test_3c3d.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/escnfs/home/mtcherny/repos/student-cse20289-fa24-mtcherny/hw/hw06/tests/test_3c3d.py", line 41, in test_nofile
    self.assertFalse("the following arguments are required" in result)
AssertionError: True is not false

======================================================================
FAIL: test_notcc (tests.test_3c3d.TestClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/escnfs/home/mtcherny/repos/student-cse20289-fa24-mtcherny/hw/hw06/tests/test_3c3d.py", line 49, in test_notcc
    self.assertFalse(".cc" in result)
AssertionError: True is not false

----------------------------------------------------------------------
Ran 10 tests in 0.457s

FAILED (failures=5)
...........
----------------------------------------------------------------------
Ran 11 tests in 2.119s

OK
